_time_format = "%Y-%m-%d %H:%M:%S %f"

# 默认unit 运行在大时长
DEFAULT_TIMEOUT = 60
ADB_DEFAULT_TIMEOUT = 30
BUG_REPORT_TIMEOUT = 600
ADB_HANDLER = 'AdbHandler'
HAND_HANDLER = 'HandHandler'
CAMERA_HANDLER = 'CameraHandler'
IMAGE_HANDLER = 'ImageHandler'
COMPLEX_HANDLER = 'ComplexHandler'
JAW_HANDLER = 'JawHandler'
PROCESSER_LIST = [ADB_HANDLER, HAND_HANDLER, CAMERA_HANDLER, JAW_HANDLER]

